aide/urls.py
# coding: utf-8
from django.urls import path, re_path

from aide import views


app_name = 'aide'
urlpatterns = [
    # Aide : liste
    path('liste', views.view_help_list, name="help-list"),

    # Aide contextuelle
    re_path('context/(?P<name>.+)', views.view_context_help, name="context"),

    # formulaire de demande
    path('contact', views.demande, name="contact"),

    # Aide : page
    re_path('(?P<path>[a-zA-Z0-9-/_]+)/(?P<pk>\d+)', views.view_help_page, name="help-accordion-page-direct"),
    re_path('(?P<path>.+)', views.view_help_page, name="help-page"),
]

configuration/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, EmailConfirmedView, CustomLogoutView)
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage


admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    # Examples:
    # path('', 'ddcs_loire.views.home', name='home'),
    # path('blog/', include('blog.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('inscription/', include('core.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('edition/', include('editeurs.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('evenements.urls')),
    path('', include('referents.urls')),
    path('parcs_naturels/', include('parcs_naturels.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('eco/', include('aide.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [path('', include('django.contrib.flatpages.urls')),
                ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

evenements/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.dashboard import TableauDeBordOrganisateur
from .views.charte import CharteCreate, CharteUpdate, CharteDiplome, CharteImpression, CharteLabel
from .views.manif import (PreambuleCreationEvenementView, ManifPublicDetail, ManifCreate, ManifDetail, ManifSend,
                          ManifUpdate, ManifFilesUpdate)
from .views.documentcomplementaire import DocumentComplementaireRequestView, DocumentComplementaireProvideView
from .views.sansinstance import SansInstanceManifCreate
from organisateurs.views.structure import StructureCreate


app_name = 'evenements'
urlpatterns = [

    # Tableau de bord principal
    path('tableau-de-bord-organisateur/', TableauDeBordOrganisateur.as_view(), name="tableau-de-bord-organisateur"),
    path('structure/add', StructureCreate.as_view(), name='structure_add'),

    # Manifestation sans type (non supporté)
    path('sansinstance/add/', SansInstanceManifCreate.as_view(), name="manif_sansinstance_add"),

    # Manifestation
    path('evenement/preambule/', PreambuleCreationEvenementView.as_view(), name='preambule_creation_evenement'),
    path('evenement/creation/', ManifCreate.as_view(), name='manif_add'),
    re_path('evenement/(?P<pk>\d+)/edition/', ManifUpdate.as_view(), name="manif_update"),
    re_path('evenement/(?P<pk>\d+)/edition_fichiers/', ManifFilesUpdate.as_view(), name="manif_files_update"),
    re_path('evenement/(?P<pk>\d+)/public/', ManifPublicDetail.as_view(), name="manif_public"),
    re_path('evenement/(?P<pk>\d+)/envoi/', ManifSend.as_view(), name="manif_send"),
    re_path('evenement/(?P<manif_pk>\d+)/charte/creation/', CharteCreate.as_view(), name="charte_add"),
    re_path('evenement/(?P<manif_pk>\d+)/charte/edition/', CharteUpdate.as_view(), name="charte_update"),
    re_path('evenement/(?P<manif_pk>\d+)/charte/diplome/', CharteDiplome.as_view(), name="charte_dipl"),
    re_path('evenement/(?P<manif_pk>\d+)/charte/impression/', CharteImpression.as_view(), name="charte_impr"),
    re_path('evenement/(?P<manif_pk>\d+)/charte/label/(?P<label>\w+)', CharteLabel.as_view(), name="charte_label"),
    re_path('evenement/(?P<manif_pk>\d+)/doc_complementaire/add', DocumentComplementaireRequestView.as_view(), name="demander_doc_complementaire"),
    re_path('evenement/(?P<pk>\d+)/', ManifDetail.as_view(), name="manif_detail"),

    re_path('doc_complementaire/(?P<pk>\d+)/', DocumentComplementaireProvideView.as_view(), name="fournir_doc_complementaire"),

]

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar
from .views.calendar import FilteredCalendar
from .views.index import HomePage
from .views.stat import Stat


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', FilteredCalendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('stat/', Stat.as_view(), name="stat"),

]

referents/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views import TableauDeBordReferent, ManifDetailReferent


app_name = 'referents'
urlpatterns = [

    # Tableau de bord principal
    path('tableau-de-bord-referent/', TableauDeBordReferent.as_view(), name="tableau-de-bord-referent"),

    # Manifestation
    re_path('referent/(?P<pk>\d+)/', ManifDetailReferent.as_view(), name="manif_detail-referent"),

]

evenements/forms/documentcomplementaire.py
# coding: utf-8

from crispy_forms.layout import Submit
from django import forms

from core.forms.base import GenericForm
from evenements.models import DocumentComplementaire


class DocumentComplementaireRequestForm(GenericForm):
    """ Formulaire """

    # Overrides
    def __init__(self, *args, **kwargs):
        super(DocumentComplementaireRequestForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', "Envoyer la Demande d'Information"))

    # Meta
    class Meta:
        model = DocumentComplementaire
        fields = ['information_requise']


class DocumentComplementaireProvideForm(GenericForm):
    """ Formulaire """

    # Overrides
    def __init__(self, *args, **kwargs):
        super(DocumentComplementaireProvideForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', "Fournir le Document"))

    # Nettoyage des données validées
    def clean_document_attache(self):
        data = self.cleaned_data['document_attache']
        if data is None:
            raise forms.ValidationError("La sélection d'un document est obligatoire")
        return data

    # Meta
    class Meta:
        model = DocumentComplementaire
        fields = ['document_attache']

evenements/views/charte.py
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, View
from django.views.generic.edit import UpdateView, CreateView
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import FileResponse

from core.util.permissions import require_role
from organisateurs.decorators import verifier_proprietaire
from ..models import Charte, Manif
from ..forms.charte import CharteForm
from configuration.directory import Paths


@method_decorator(require_role('organisateur'), name='dispatch')
class CharteCreate(CreateView):
    """ Création de manifestation """

    # Configuration
    model = Charte
    form_class = CharteForm

    # Overrides
    def form_valid(self, form):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        form.instance.manif = manif
        user = manif.structure.organisateur.user
        manif.actions.create(user=user, action="questionnaire de la charte rempli")
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['manif_pk'] = self.kwargs['manif_pk']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['manif'] = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        return context

    def get_success_url(self):
        return reverse('evenements:manif_detail', kwargs={'pk': self.object.manif.pk})


class CharteUpdate(UpdateView):
    """ Modifier une manifestation """

    # Configuration
    model = Charte
    form_class = CharteForm

    # Overrides
    @method_decorator(verifier_proprietaire)
    def dispatch(self, *args, **kwargs):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        # Vérifier si la manifestation est finalisée
        if manif.finalise:
            return render(self.request, "core/notification.html",
                          {'title': "Editer la charte", 'message': "L'édition n'est plus possible !", 'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        return manif.charte

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['manif_pk'] = self.kwargs['manif_pk']
        return kwargs

    def get_success_url(self):
        return reverse('evenements:manif_detail', kwargs={'pk': self.object.manif.pk})


class CharteDiplome(TemplateView):
    """ Page de remise du diplôme """

    template_name = 'evenements/charte_diplome.html'

    @method_decorator(verifier_proprietaire)
    def dispatch(self, *args, **kwargs):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        # Vérifier si la manifestation est finalisée
        if not manif.finalise:
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme", 'message': "Le diplôme est accessible seulement quand la déclaration est finalisée !", 'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        elif manif.date_fin < timezone.now():
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme",
                           'message': "La manifestation est manitenant terminée !",
                           'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        elif manif.charte.diplome() == "echec":
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme",
                           'message': "La manifestation n'a pas obtenu une note suffisante à l'obtention d'un diplôme !",
                           'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        context['manif'] = manif
        context['diplome'] = manif.charte.diplome()
        context['date'] = timezone.now()
        return context


class CharteImpression(TemplateView):
    """ Page de présentation de la charte pour impression """

    template_name = 'evenements/charte_impression.html'

    @method_decorator(verifier_proprietaire)
    def dispatch(self, *args, **kwargs):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        # Vérifier si la manifestation est finalisée
        if not manif.finalise:
            return render(self.request, "core/notification.html",
                          {'title': "Imprimer la charte", 'message': "La charte est accessible seulement quand la déclaration est finalisée !", 'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        elif manif.date_fin < timezone.now():
            return render(self.request, "core/notification.html",
                          {'title': "Imprimer la charte",
                           'message': "La manifestation est manitenant terminée !",
                           'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        context['manif'] = manif
        context['diplome'] = manif.charte.diplome()
        context['date'] = timezone.now()
        return context


class CharteLabel(View):
    """ Vue de téléchargement des labels """

    @method_decorator(verifier_proprietaire)
    def dispatch(self, *args, **kwargs):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        # Vérifier si la manifestation est finalisée
        if not manif.finalise:
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme", 'message': "Le diplôme est accessible seulement quand la déclaration est finalisée !", 'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        elif manif.date_fin < timezone.now():
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme",
                           'message': "La manifestation est manitenant terminée !",
                           'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        elif manif.charte.diplome() == "echec":
            return render(self.request, "core/notification.html",
                          {'title': "Editer le diplôme",
                           'message': "La manifestation n'a pas obtenu une note suffisante à l'obtention d'un diplôme !",
                           'type': 1,
                           'suite': 'evenements:tableau-de-bord-organisateur'})
        return super().dispatch(*args, **kwargs)

    def get(self, request, **kwargs):
        manif = get_object_or_404(Manif, pk=self.kwargs['manif_pk'])
        diplome = manif.charte.diplome()
        file = Paths.get_root_dir('portail', 'static', 'portail', 'img')
        if diplome == 'or':
            file += 'Or'
        elif diplome == 'argent':
            file += 'Argent'
        else:
            file += 'Bronze'
        if self.kwargs['label'] == 'blanc':
            file += '.jpg'
        else:
            file += '.png'
        return FileResponse(open(file, 'rb'), as_attachment=True)

evenements/views/dashboard.py
# coding: utf-8
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from core.util.permissions import require_role
from evenements.models import Manif
from organisateurs.models.structure import Structure


class TableauDeBordOrganisateur(ListView):
    """ Tableau de bord organisateur """

    # Configuration
    model = Manif
    template_name = 'evenements/dashboard.html'

    # Overrides
    @method_decorator(require_role('organisateur'))
    def dispatch(self, *args, **kwargs):
        """ Protéger la vue pour un accès par les organisateurs uniquement """
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        """ Renvoyer les manifestations à afficher dans le tableau de bord """
        try:
            user_structure = self.request.user.organisateur.structure
        except Structure.DoesNotExist:
            user_structure = None
        return Manif.objects.filter(structure=user_structure).order_by('-pk')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

evenements/templates/evenements/charte_diplome.html
{% extends "base.html" %}


{% load i18n static %}

{% block extra_js %}
    <script src="{% static 'libs/fontawesome-pro/js/all.js' %}" type="text/javascript"></script>
{% endblock %}

{% block head_title %}
    Diplôme
{% endblock %}

{% block page_title %}
    <h1> Diplôme d'éco-manifestation obtenu par la manifestation {{ manif }}</h1>
{% endblock %}

{% block content %}
    <div class="page_diplome">
        <img src="{% static 'portail/img/Diplome_Ecomanif_v3.jpg' %}" width="1200px">
        <div class="diplome_label">
            {% if diplome == "or" %} <img src="{% static 'portail/img/Or.jpg' %}"
            {% elif diplome == "argent" %} <img src="{% static 'portail/img/Argent.jpg' %}"
            {% elif diplome == "bronze" %} <img src="{% static 'portail/img/Bronze.jpg' %}"
            {% endif %} width="500px">
        </div>
        <div class="diplome_ecrit h1">
            <p>
                Aux vues des actions cochées dans le formulaire de cette manifestation,
                la plateforme "EcoManifestation" décerne le diplôme <strong>{{ diplome }}</strong>
                à la manifestation :<br><span class="d-block text-center py-2"><strong>{{ manif }}</strong></span>
                organisée par <strong>{{ manif.structure }}</strong>
            </p>
            <br>
            <p class="h3">
                Manifestation de {{ manif.activite }} du {{ manif.date_debut }} au {{ manif.date_fin }}
                se déroulant à {{ manif.ville_depart }}.<br>
                Elle traverse le ou les parcs :
                {% for parc in manif.parcs.all %}
                    {% if forloop.last %}
                        {{ parc }}.
                    {% else %}
                        {{ parc }},
                    {% endif %}
                {% endfor %}
            </p>
            <p class="h1 diplome_date">Fait le {{ date }}</p>
        </div>
    </div>
    <div class="row boutons">
        <div class="col-md-auto">
            <a href="#" OnClick="javascript:window.print()" class="btn btn-outline-primary btn-fill mt-4 mb-2"
               role="button">
                <i class="imprimer"></i> Imprimer le diplôme
            </a><br>
            Télécharger le logo :
            <a href="{% url 'evenements:charte_label' manif.pk 'blanc' %}" target="_blank"
               class="btn btn-outline-primary mb-1" role="button">
                <i class="telecharger"></i> sur fond blanc
            </a>
            <a href="{% url 'evenements:charte_label' manif.pk 'trans' %}" target="_blank"
               class="btn btn-outline-primary mb-1" role="button">
                <i class="telecharger"></i> sur fond transparent
            </a>
        </div>
        <div class="col-md-auto ml-lg-auto">
            <a href="{% url 'evenements:manif_detail' manif.pk %}" class="btn btn-outline-primary btn-fill mt-4"
               role="button">
                <i class="retour"></i> Revenir à la manifestation
                <i class="dossier left-margin"></i>
            </a>
        </div>
    </div>
{% endblock %}

evenements/templates/evenements/documentcomplementaire_form.html
{% extends "base_form.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}

{% block head_title %}
    {% if manif %}
        Demande de complément d'information pour la manifestation "{{ manif }}"
    {% else %}
        Envoi de complément d'information pour la manifestation "{{ object.manif }}"
    {% endif %}
{% endblock %}

{% block page_title %}
    {% if manif %}
        <h1>Demande de complément d'information pour la manifestation "{{ manif }}"</h1>
    {% else %}
        <h1>Envoi des documents suivants : <small>{{ object.information_requise }}</small></h1>
    {% endif %}
{% endblock %}

evenements/templates/evenements/evenement_detail.html
{% extends "base.html" %}


{% load i18n file_tags %}

{% block head_title %}
    EcoManifestation
{% endblock %}

{% block resume %}
    {% include 'evenements/blocs/bandeau_resume.html' with manif=object %}
{% endblock %}

{% block fil_ariane %}
    {% if request.user.organisateur %}
        {% include 'evenements/blocs/bandeau_fil_ariane.html' %}
        {% if not object.finalise %}
            {% include 'evenements/blocs/bandeau_delai_manif.html' %}
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="tab-list col-lg-12">
            <ul class="nav nav-tabs" id="onglet">
                <li class="nav-item"><a class="nav-link active" href="#event" data-toggle="tab">Détail de la manifestation</a></li>
                {% include 'evenements/panneaux/onglets.html' %}
            </ul>
        </div>
        <div class="col-lg-8">
            <div class="tab-content">
                {% include 'evenements/panneaux/organisateur.html' %}
            </div>
        </div>
        <div class="col-lg-4">
            {% if requis  %}
            <div class="card border-danger side mb-3">
                <div class="card-header bg-danger">
                        <i class="action-requise-blanc"></i>Actions requises
            {% else %}
            <div class="card border-primary side mb-3">
                <div class="card-header bg-primary">
                        <i class="action-requise-blanc"></i>Actions possibles
            {% endif %}
                </div>
                <div class="card-body">
                    {% if action == 'rien' %}<p>Pas d'actions possibles</p>{% endif %}
                    {% if action == 'contact' %}<p style="color: red;">La date limite d'envoi de la déclaration est dépassée.<br>Veuillez prendre contact avec le référent de votre département.</p>{% endif %}
                    {% if action == 'echec' %}
                        <p style="color: red;">Le score de la charte est insuffisant pour envoyer votre déclaration.<br>
                            Vous devez au minimum, réaliser les actions obligatoires de chaque thématique.<br><br>
                            <a href="{% url 'evenements:charte_update' manif_pk=object.id %}"
                               class="btn btn-primary btn-break" role="button"><i class="editer"></i> Editer votre charte</a>
                        </p>
                    {% endif %}
                    {% if action == 'charte' %}
                        <a href="{% url 'evenements:charte_add' manif_pk=object.id %}" class="btn btn-primary btn-break" role="button">
                            <i class="evaluer"></i> Evaluer votre EcoManifestation
                        </a>
                    {% endif %}
                    {% if action == 'envoi' %}
                        <a href="{% url 'evenements:manif_send' pk=object.id %}" class="btn btn-primary btn-break" role="button">
                            <i class="envoyer"></i> Envoyer la déclaration
                        </a>
                    {% endif %}
                    {% if action == 'diplome' %}
                        <a href="{% url 'evenements:charte_dipl' manif_pk=object.id %}" class="btn btn-primary btn-break" role="button">
                            <i class="diplome"></i> Accéder à votre diplôme
                        </a>
                        <br>
                        <a href="/eco/pack{{ user.get_departement.name }}" class="btn btn-primary btn-break mt-4" role="button">
                            <i class="diplome"></i> Accéder au pack Éco-Évènement
                        </a>
                    {% endif %}
                    {% if action == 'manquants' %}
                        <p style="color: red;">Le dossier de la manifestation est incomplet:<br>
                        Une fois les points listés réglés, vous serez en mesure d'envoyer votre demande.
                        <ul>
                            {% for fichier in object.liste_manquants %}
                                    {% if fichier == "formulaire incomplet" %}
                                        <a href="{% url 'evenements:manif_update' pk=object.id %}" class="btn btn-primary btn-break" role="button"><i class="editer"></i> Editer le formulaire</a>
                                    {% else %}
                                        <li>{{ fichier }}</li>
                                    {% endif %}
                           {% endfor %}
                        </ul>
                        </p>
                    {% endif %}
                    {% if request.user.referent %}
                        <a href="{% url 'evenements:demander_doc_complementaire' manif_pk=object.id %}" class="btn btn-primary btn-break" role="button">
                            <i class="ajouter"></i> Demander plus d'informations
                        </a>
                    {% endif %}
                </div>
            </div>
            {% if doc %}
                <div class="card border-danger mb-3">
                    <div class="card-header bg-danger">
                        <i class="doc"></i>Des documents complémentaires sont requis par le référent du département
                    </div>
                    <div class="card-body">
                        <p style="color: red;">Veuillez fournir les documents dont la liste est affichée ci-dessous</p>
                        <ul class="list-group">
                            {% for additional_data in object.get_docs_complementaires_manquants %}
                                <li class="list-group-item">
                                    <a href="{% url 'evenements:fournir_doc_complementaire' pk=additional_data.pk %}">{{ additional_data }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <br>
            {% endif %}
            {% include 'evenements/side_bar/score_charte.html' %}

            {% if request.user.organisateur %}
                <a href="{% url 'evenements:tableau-de-bord-organisateur' %}" class="btn btn-outline-secondary btn-fill btn-break mt-4" role="button">
                    <i class="retour"></i> Revenir au tableau de bord
                    <i class="tableau-de-bord left-margin"></i>
                </a>
            {% else %}
                <a href="{% url 'referents:tableau-de-bord-referent' %}" class="btn btn-outline-secondary btn-fill btn-break mt-4" role="button">
                    <i class="retour"></i> Revenir au tableau de bord
                    <i class="tableau-de-bord left-margin"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

evenements/templates/evenements/evenementpublic_detail.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}{{ object|capfirst }}{% endblock %}
{% block page_title %}
    <h1>{{ object|capfirst }}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card ">
                {% if not object.visible_dans_calendrier %}
                    <div class="card-body"><span class="text-danger">La manifestation a été masquée du calendrier public par l'{{ object.prive | yesno:"organisateur,instructeur" }}</span></div>
                {% endif %}
                <div class="card-body">{{ object.description|linebreaks }}</div>
                <ul class="list-group">
                    <li class="list-group-item"><strong><i class="date"></i>Début : </strong>{{ object.date_debut|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="date"></i>Fin : </strong>{{ object.date_fin|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="activite"></i> Sport : </strong>{{ object.activite.discipline }} - {{ object.activite }}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Commune de départ : </strong>{{ object.ville_depart|capfirst }}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> parcs traversés : </strong>
                        {% for parc in object.parcs.all %}
                            {% if forloop.last %}
                                {{ parc }}.
                            {% else %}
                                {{ parc }},
                            {% endif %}
                        {% endfor %}
                    </li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Communes traversées : </strong>
                        {% for ville in object.get_villes_traversees %}
                            {% if forloop.last %}
                                {{ ville }}.
                            {% else %}
                                {{ ville }},
                            {% endif %}
                        {% endfor %}
                    </li>
                </ul>
            {% if object.afficher_adresse_structure %}
                <div class="card-body">
                    <strong>Informations de contact :</strong><br>
                    {% with object.structure as structure %}
                        {{ structure.name }}<br>
                        {{ structure.address }}<br>
                        <span id="ctx-help-insee-code">{{ structure.commune.code }}</span> {{ structure.commune }}<br>
                        {% if structure.website %}<strong>Site web :</strong> {{ structure.website|urlize }}<br>{% endif %}
                        <strong>Téléphone :</strong> {{ structure.phone }}<br>
                    {% endwith %}

                </div>
            {% endif %}
            </div>
        </div>
        {% comment %}
        <div class="col-sm-6">
            {% include 'events/map.html' %}
        </div>
        {% endcomment %}
    </div>
    {% if object.get_type_manif %}
        <a href="{% url 'portail:calendar' %}" class="btn btn-primary">
            <i class="date"></i> Retour au calendrier des manifestations sportives</a>
    {% else %}
        <a href="{% url 'evenements:tableau-de-bord-organisateur' %}" class="btn btn-primary">
            <i class="tableau-de-bord"></i> Retour au tableau de bord</a>
    {% endif %}
{% endblock %}